<?php

namespace Proxies\__CG__\AppBundle\Entity\Extrablog;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WpPosts extends \AppBundle\Entity\Extrablog\WpPosts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postAuthor', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postDate', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postDateGmt', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postContent', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postTitle', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postExcerpt', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postStatus', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'commentStatus', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'pingStatus', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postPassword', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postName', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'toPing', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'pinged', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postModified', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postModifiedGmt', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postContentFiltered', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postParent', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'guid', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'menuOrder', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postType', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postMimeType', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'commentCount'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postAuthor', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postDate', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postDateGmt', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postContent', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postTitle', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postExcerpt', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postStatus', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'commentStatus', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'pingStatus', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postPassword', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postName', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'toPing', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'pinged', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postModified', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postModifiedGmt', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postContentFiltered', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postParent', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'guid', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'menuOrder', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postType', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'postMimeType', '' . "\0" . 'AppBundle\\Entity\\Extrablog\\WpPosts' . "\0" . 'commentCount'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WpPosts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostAuthor', []);

        return parent::getPostAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostAuthor($postAuthor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostAuthor', [$postAuthor]);

        return parent::setPostAuthor($postAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDate', []);

        return parent::getPostDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDate(\DateTime $postDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDate', [$postDate]);

        return parent::setPostDate($postDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDateGmt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDateGmt', []);

        return parent::getPostDateGmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDateGmt(\DateTime $postDateGmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDateGmt', [$postDateGmt]);

        return parent::setPostDateGmt($postDateGmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContent', []);

        return parent::getPostContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContent($postContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContent', [$postContent]);

        return parent::setPostContent($postContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostTitle', []);

        return parent::getPostTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostTitle($postTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostTitle', [$postTitle]);

        return parent::setPostTitle($postTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostExcerpt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostExcerpt', []);

        return parent::getPostExcerpt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostExcerpt($postExcerpt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostExcerpt', [$postExcerpt]);

        return parent::setPostExcerpt($postExcerpt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostStatus', []);

        return parent::getPostStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostStatus($postStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostStatus', [$postStatus]);

        return parent::setPostStatus($postStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentStatus', []);

        return parent::getCommentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentStatus($commentStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentStatus', [$commentStatus]);

        return parent::setCommentStatus($commentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPingStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPingStatus', []);

        return parent::getPingStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPingStatus($pingStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPingStatus', [$pingStatus]);

        return parent::setPingStatus($pingStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostPassword', []);

        return parent::getPostPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostPassword($postPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostPassword', [$postPassword]);

        return parent::setPostPassword($postPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostName', []);

        return parent::getPostName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostName($postName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostName', [$postName]);

        return parent::setPostName($postName);
    }

    /**
     * {@inheritDoc}
     */
    public function getToPing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToPing', []);

        return parent::getToPing();
    }

    /**
     * {@inheritDoc}
     */
    public function setToPing($toPing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToPing', [$toPing]);

        return parent::setToPing($toPing);
    }

    /**
     * {@inheritDoc}
     */
    public function getPinged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPinged', []);

        return parent::getPinged();
    }

    /**
     * {@inheritDoc}
     */
    public function setPinged($pinged)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPinged', [$pinged]);

        return parent::setPinged($pinged);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostModified', []);

        return parent::getPostModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostModified(\DateTime $postModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostModified', [$postModified]);

        return parent::setPostModified($postModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostModifiedGmt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostModifiedGmt', []);

        return parent::getPostModifiedGmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostModifiedGmt(\DateTime $postModifiedGmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostModifiedGmt', [$postModifiedGmt]);

        return parent::setPostModifiedGmt($postModifiedGmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContentFiltered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContentFiltered', []);

        return parent::getPostContentFiltered();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContentFiltered($postContentFiltered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContentFiltered', [$postContentFiltered]);

        return parent::setPostContentFiltered($postContentFiltered);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostParent', []);

        return parent::getPostParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostParent($postParent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostParent', [$postParent]);

        return parent::setPostParent($postParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuid', []);

        return parent::getGuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuid($guid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuid', [$guid]);

        return parent::setGuid($guid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuOrder', []);

        return parent::getMenuOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuOrder($menuOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuOrder', [$menuOrder]);

        return parent::setMenuOrder($menuOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostType', []);

        return parent::getPostType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostType($postType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostType', [$postType]);

        return parent::setPostType($postType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostMimeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostMimeType', []);

        return parent::getPostMimeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostMimeType($postMimeType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostMimeType', [$postMimeType]);

        return parent::setPostMimeType($postMimeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentCount', []);

        return parent::getCommentCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentCount($commentCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentCount', [$commentCount]);

        return parent::setCommentCount($commentCount);
    }

}
