<?php

namespace AppBundle\Repository\Extrasolar;


use Doctrine\ORM\EntityRepository;

/**
 * PublicityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicityRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByLocation($location)
  {
      return $this->createQueryBuilder('p')
            ->Where('p.location = :loc AND p.disable = false')
            ->SetParameter('loc',$location)
            ->getQuery()
            ->getResult()
            ;
  }

}
